# Wojciech Pragłowski

## Numpy basics

Guidlines:
1. Write a function that will check whether the given matrix contains a given value.
1. Write a function that will return the mean, median, and mode (mode).
1. Write a function that will generate a matrix of given sizes with the same numerical value.
1. Write a function that changes all negative values in the matrix to 0.
1. Write a function that will check if the given matrix X with size 2x2 is a solution of the matrix equation ax^2 + bx + c = 0, where a, b, c are given numerical values.
1. Write a function that will calculate the nth Fibonacci number using matrix exponentiation [[1,1],[1,0]] (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Macierze_liczb_Fibonacciego).
1. Write a function that will calculate the nth Fibonacci number using the Binet formula (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Wz%C3%B3r_Bineta).
1. Write a function that will generate a matrix with random elements (integers from a given range) with a predetermined value of the matrix trace.
1. Write a function that will generate a matrix with random elements (integers from a given range) with predetermined eigenvalues. Possible to use Cayley-Hamilton.

In [1]:
import numpy as np

#### Exercise 1

In [3]:
def find_value(value, given_array):
    check = np.isin(given_array, value)
    print(check)
    
arr = np.arange(6).reshape((2,3))
find_value(2, arr)

[[False False  True]
 [False False False]]


#### Exercise 2

In [14]:
def maths_returning(given_array):
    values, counts = np.unique(given_array, return_counts = True)
    index = np.argmax(counts)
    print("Średnia:", np.mean(given_array),"\nMediana: ", np.median(given_array), "\nDominanta: ", values[index])
    
arr = np.array([[1,2,5],[2,5,5],[9,-1,-5]])
arr2 = np.arange(9).reshape(3,3)
maths_returning(arr)

Średnia: 2.5555555555555554 
Mediana:  2.0 
Dominanta:  5


#### Exercise 3

In [20]:
def generate_array(height,width, value):
    new_array = np.empty(shape=(height,width), dtype=int)
    for i in range(height):
        for j in range(width):    
            new_array[i] = value
    return new_array

generate_array(5, 7, 6)

array([[6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6]])

#### Exercise 4

In [27]:
def change_negative(given_array):
    new_array = np.where(given_array<0, 0, given_array)
    return new_array

arr = np.array([[1,2,3], [-1,-2,-3], [1,-2,3]])
change_negative(arr)

array([[1, 2, 3],
       [0, 0, 0],
       [1, 0, 3]])

#### Exercise 5

In [39]:
def check_equation(given_array, a, b, c):
    result = (a*given_array**2) + b*given_array + c
    if np.mean(result) == 0:
        return print("Podana macierz JEST rozwiązaniem równania!\n", result)
    else:
        return print("Niestety podana macierz nie rozwiązuje powyższego równania...\n", result)

arr = np.array([[1,1], [1,1]])
check_equation(arr, 1, -1, 0)

Podana macierz JEST rozwiązaniem równania!
 [[0 0]
 [0 0]]


#### Exercise 6

In [12]:
def array_fibonacci(n):
    begin_array = np.array([[1, 1], [1, 0]])
    values, vectors = np.linalg.eig(begin_array)
    Fn = vectors @ np.diag(values ** n) @ vectors.T
    return int(np.rint(Fn[0, 1]))

array_fibonacci(15)

610

#### Exercise 7

In [23]:
def binet_fib(n):
    result = 1/np.sqrt(5)*(((1+np.sqrt(5))/2)**n)
    return round(result,2)

binet_fib(10)

55.0

#### Exercise 8

In [33]:
def random_trace(size, trace_value):
    diag = []
    for i in trace_value:
        if i == 0: 
            diag.append([0 for i in range(size)])
            continue
        total = i
        temp = []
        for i in range(size-1):
            rand_value = np.random.randint(0, total)
            temp.append(rand_value)
            total -= rand_value
        temp.append(total)
        diag.append(temp)
    new_array = np.diagflat(diag)
    final_array = np.where(new_array == 0, np.random.randint(9), new_array)
    return final_array
    
trace_value = [15]
random_trace(4, trace_value)

array([[2, 8, 8, 8],
       [8, 5, 8, 8],
       [8, 8, 5, 8],
       [8, 8, 8, 3]])

#### Exercise 9 

In [32]:
def array_det(size, det_value):
    diag = []
    for i in det_value:
        if i == 0: 
            diag.append([0 for i in range(size)])
            continue
        total = i
        temp = []
        for i in range(size-1):
            rand_value = np.random.randint(0, total)
            temp.append(rand_value)
            total -= rand_value
        temp.append(total)
        diag.append(temp)
        new_array = np.array(diag).reshape(2,2)
        return new_array
        
array_det(4,[8])

array([[4, 3],
       [0, 1]])